# Receivers collect telemetry from one or more sources.
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318

# Extensions are optional components that expand the capabilities of
# the Collector to accomplish tasks not directly involved with processing
# telemetry data. For example, you can add extensions for Collector health
# monitoring, service discovery, or data forwarding, among others

# extensions:
#   health_check:
#   pprof:
#   zpages:

# Processors take the data collected by receivers and modify or transform it before sending it to the exporters.
processors:
  batch:

# Exporters send data to one or more backends or destinations.
exporters:
  # Data sources: traces, metrics, logs
  otlp:
      endpoint: localhost:4317
      tls:
        insecure: true

  # Data sources: traces
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  # Data sources: traces
  zipkin:
    endpoint: "zipkin:9411/api/v2/spans" # Send traces to Zipkin

  # Data sources: traces, metrics, logs
  # NOTE: Prior to v0.86.0 use `logging` instead of `debug`
  debug:
    verbosity: detailed

service:
  # extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, otlp/jaeger, zipkin, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, debug]
